services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/server:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./config/server/conf.d/:/etc/clickhouse-server/conf.d/
      # - ./config/users.xml:/etc/clickhouse-server/users.xml
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    depends_on:
      - clickhouse-keeper

  clickhouse-keeper:
    image: 'clickhouse/clickhouse-keeper'
    hostname: clickhouse-keeper
    volumes:
      - ./data/keeper:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-keeper
      - ./config/keeper/conf.d/:/etc/clickhouse-keeper/conf.d/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
